//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置.xlsx SHEET: 关卡配置
	 */
	export class battleTable {
		/**
		 * 章节
		 */
		chapter: number;
		/**
		 * 关卡
		 */
		level: number;
		/**
		 * 怪物组
		 */
		monsterAry: battleTable.MonsterAryItem[];

		GetType(): string { return 'table.battleTable'; }
	}
	export module battleTable {
		export class MonsterAryItem {
			monsterID: number;
			rate: number;
		}
	}
}
