//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置.xlsx SHEET: 物品配置 KEY: id
	 */
	export class PropTable {
		id: number;
		/**
		 * 名称
		 */
		name: string;
		/**
		 * 图片源
		 */
		source: string;
		/**
		 * 价格
		 */
		price: number;
		/**
		 * 参数1
		 */
		vars1: string;

		GetType(): string { return 'table.PropTable'; }
	}
}
