//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置.xlsx SHEET: 任务配置 KEY: id
	 */
	export class TaskTable {
		id: number;
		/**
		 * 任务说明
		 */
		taskContent: string;
		/**
		 * 奖励物品ID
		 */
		awardID: number;
		/**
		 * 奖励数量
		 */
		awardNum: number;
		/**
		 * 任务等级
		 */
		taskLevel: number;

		GetType(): string { return 'table.TaskTable'; }
	}
}
