//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置.xlsx SHEET: 宝箱配置
	 */
	export class TreasureTable {
		id: number;
		/**
		 * 名称
		 */
		name: string;
		/**
		 * 完成任务条件
		 */
		condition: string;
		/**
		 * 奖励物品ID
		 */
		awardID: number;
		/**
		 * 奖励数量
		 */
		awardNum: number;
		/**
		 * 宝箱等级
		 */
		level: number;
		/**
		 * 图片源
		 */
		render: string[];

		GetType(): string { return 'table.TreasureTable'; }
	}
}
