//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置.xlsx SHEET: 转盘配置 KEY: id
	 */
	export class TurntableList {
		id: number;
		/**
		 * 旋转角度
		 */
		rotation: number;
		/**
		 * 图片名字
		 */
		source: string;
		/**
		 * 描述
		 */
		dec: string;
		/**
		 * 获得金币数量
		 */
		money: number;
		/**
		 * 命中率
		 */
		hitRate: number;

		GetType(): string { return 'table.TurntableList'; }
	}
}
