//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置.xlsx SHEET: 夹子配置 KEY: id
	 */
	export class ClipTable {
		id: number;
		/**
		 * 夹子名称
		 */
		name: string;
		/**
		 * 渲染源
		 */
		render: string;
		/**
		 * 命中率
		 */
		hitRate: number;
		/**
		 * 伤害
		 */
		hurt: number;
		/**
		 * 动作前摇
		 */
		actionBefore: number;
		/**
		 * 等级
		 */
		level: number;
		/**
		 * 伤血持续时间
		 */
		hurtDuration: number[];

		GetType(): string { return 'table.ClipTable'; }
	}
}
