//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置.xlsx SHEET: 商店配置
	 */
	export class ShopTable {
		id: number;
		/**
		 * 物品ID
		 */
		itemID: number;
		/**
		 * 是否热销
		 */
		isHot: number;

		GetType(): string { return 'table.ShopTable'; }
	}
}
