//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 游戏配置.xlsx SHEET: 场景道具配置
	 */
	export class ScenePropTable {
		id: number;
		/**
		 * 名称
		 */
		name: string;
		/**
		 * 图片
		 */
		imageAry: string[];
		/**
		 * 影片剪辑
		 */
		movieClipAry: ScenePropTable.MovieClipAryItem[];
		/**
		 * 龙骨
		 */
		dragonBonesName: string;
		/**
		 * 碰撞体
		 */
		colliderAry: ScenePropTable.ColliderAryItem[];

		GetType(): string { return 'table.ScenePropTable'; }
	}
	export module ScenePropTable {
		export class MovieClipAryItem {
			keyName: string;
			groupName: string;
			actionName: string;
			frameRate: number;
		}
	}
	export module ScenePropTable {
		export class ColliderAryItem {
			posX: number;
			posY: number;
			radius: number;
		}
	}
}
